# Generated by Django 4.2.1 on 2023-05-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
